theme: jekyll-theme-minimal
title: Neural Style Transfer
logo: Utils/it_10.png
description: Project carried out by ETSETB students as part of the Deep Learning for Artificial Intelligence subject. This notebook contains the research and discussion performed of the state-of-the-art NST techniques.

